/* the tables of the club are not named by their hosts: each one draws its
   name from the register below, a hundred works, pits, wharves and inns of
   the Midlands around 1800. A name in use at another live table is skipped
   while any remain free. */

export const TABLE_NAMES: readonly string[] = [
  'Soho Foundry',
  'Coalbrookdale',
  'Etruria Works',
  'Cromford Mill',
  'Bridgewater Wharf',
  'Albion Mill',
  'Round Foundry',
  'Bersham Ironworks',
  'Ketley Forge',
  'Horsehay Works',
  'Bedlam Furnaces',
  'Wedgwood Kilns',
  'Spode Yard',
  'Longton Pottery',
  'Burslem Bottle Ovens',
  'Chesterfield Canal',
  'Trent Lock',
  'Fazeley Junction',
  'Gas Street Basin',
  'Stourport Basin',
  'Shardlow Wharf',
  'Wolverton Cut',
  'Foxton Locks',
  'Harecastle Tunnel',
  'Dudley Tunnel',
  'Netherton Furnace',
  'Tipton Green',
  'Bilston Ironworks',
  'Wednesbury Pits',
  'Walsall Tannery',
  'Dudley Glassworks',
  'Stourbridge Glasshouse',
  'Red House Cone',
  'Brierley Hill',
  'Gornal Colliery',
  'Cannock Chase',
  'Hednesford Pit',
  'Brownhills Colliery',
  'Bloxwich Furnace',
  'Willenhall Locksmiths',
  'Darlaston Gun Barrels',
  'Smethwick Pumphouse',
  'Handsworth Mint',
  'Aston Flint Glass',
  'Digbeth Tannery',
  'Jewellery Quarter',
  'Deritend Forge',
  'Bordesley Mill',
  'Sarehole Mill',
  'Perrott’s Folly',
  'Cradley Chainshop',
  'Halesowen Nailers',
  'Lye Waste',
  'Kinver Rock Houses',
  'Bewdley Quay',
  'Kidderminster Looms',
  'Stourbridge Lion',
  'Coventry Silk Hall',
  'Nuneaton Brickyard',
  'Bedworth Pits',
  'Tamworth Castle Mill',
  'Fazeley Cotton Mill',
  'Burton Brewhouse',
  'Bass Maltings',
  'Tutbury Mill',
  'Uttoxeter Cattle Fair',
  'Cheadle Copperworks',
  'Froghall Wharf',
  'Caldon Lime Kilns',
  'Leek Silk Mill',
  'Macclesfield Bridge',
  'Stone Brewery',
  'Stafford Shoemakers',
  'Shugborough Hall',
  'Cannock Mill',
  'Rugeley Tanyard',
  'Lichfield Close',
  'Whittington Barracks',
  'Ashby Canal',
  'Moira Furnace',
  'Swadlincote Potbank',
  'Derby Silk Mill',
  'Belper Mill',
  'Milford Mills',
  'Darley Abbey',
  'Butterley Ironworks',
  'Codnor Park',
  'Ripley Foundry',
  'Ilkeston Pit',
  'Long Eaton Lace',
  'Nottingham Lace Market',
  'Wollaton Pit',
  'Papplewick Pumping',
  'Bestwood Colliery',
  'Worcester Porcelain',
  'Droitwich Brine Pits',
  'Redditch Needle Mill',
  'Forge Mill',
  'Warwick Wharf',
  'Hatton Flight',
  'Leamington Pump Room',
  'Rugby Iron Bridge',
  'Bull Ring Market',
];

/** a name not sitting on any live table; any name when all hundred are busy */
export function pickTableName(taken: Iterable<string>, random: () => number = Math.random): string {
  const busy = new Set(taken);
  const free = TABLE_NAMES.filter((n) => !busy.has(n));
  const pool = free.length ? free : TABLE_NAMES;
  return pool[Math.floor(random() * pool.length)] ?? TABLE_NAMES[0];
}
