/* Bibliothèque partagée « Club Industriel » (design.md §7) — point d'entrée. */
export { default as Button } from './Button';
export type { ButtonProps, ButtonVariant } from './Button';
export { default as SeatToken } from './SeatToken';
export type { SeatTokenProps } from './SeatToken';
export { default as TableCard } from './TableCard';
export type { TableCardProps } from './TableCard';
export { default as ModeCard } from './ModeCard';
export type { ModeCardProps } from './ModeCard';
export { default as QueuePanel } from './QueuePanel';
export type { QueuePanelProps } from './QueuePanel';
export { default as RankBadge } from './RankBadge';
export type { RankBadgeProps, RankTier } from './RankBadge';
export { default as CodeInput } from './CodeInput';
export type { CodeInputProps } from './CodeInput';
export { default as ActivityFeedItem } from './ActivityFeedItem';
export type { ActivityFeedItemProps } from './ActivityFeedItem';
export { default as StatTile } from './StatTile';
export type { StatTileProps } from './StatTile';
export { default as EmptyState } from './EmptyState';
export type { EmptyStateProps } from './EmptyState';
export { default as Skeleton } from './Skeleton';
export type { SkeletonProps } from './Skeleton';
export { default as Tabs } from './Tabs';
export type { TabsProps, TabItem } from './Tabs';
export { default as Modal } from './Modal';
export type { ModalProps } from './Modal';
export { default as Toast } from './Toast';
export type { ToastData } from './Toast';
export { default as PlatformShell } from './PlatformShell';
export { default as MemberAvatar, FrameRing } from './MemberAvatar';
export type { MemberAvatarProps } from './MemberAvatar';
export { usePresence } from './presence';
export type { PresenceSnapshot, QueueSnapshot } from './presence';
